### ISSUE TITLE
Avoid the boolean trap

### ISSUE THREAD

**Issue by mathiasbynens** [jcranmer/idna-uts46#1]
E.g. https://github.com/jcranmer/idna-uts46#uts46toasciidomain-transitionalfalse-usestd3asciifalse How about accepting an `options` object as the second parameter instead?

See http://ariya.ofilabs.com/2011/08/hall-of-api-shame-boolean-trap.html.

**Comment by jcranmer** [comment]
Fixed by c40a67a770.
