### ISSUE TITLE
Problem mapping harambe character + other new iOS emojis

### ISSUE THREAD

**Issue by jonroig** [jcranmer/idna-uts46#3]
Hi there... love the effort you've put into this project. Works great, except the new iOS-approved emojis don't decode correctly.

This character is an example: http://emojipedia.org/gorilla/

uts46.toAscii(🦍) throws an error

I tried to regenerate the idna-map.js with the python script using using http://www.unicode.org/Public/idna/9.0.0/ as a source, but that doesn't seem to have helped... what did I miss there?

Thanks!

**Comment by jcranmer** [comment]
I've fixed #7 , which updated to Unicode 9. Running uts46.toAscii now returns xn--dt9h.
