### ISSUE TITLE
Request for dependency bump (punycode library)

### ISSUE THREAD

**Issue by KaiSchwarz-cnic** [jcranmer/idna-uts46#4]
Hi jcranmer!

there have been some fixes added to the punycode library, but your versioning in package.json only considers version 1.4.1 at max. The most updated version of punycode.js is 2.1.0.
Read: https://github.com/bestiejs/punycode.js/issues/12#issuecomment-270964427

Would be great if you can do a dependency bump to reflect the changes also in your library.

Thanks!

**Comment by jcranmer** [comment]
I've updated this with commit 96013fab3adb78bf29c1e937e1adc99233407187
