### ISSUE TITLE
verifyDNSLength Support

### ISSUE THREAD

**Issue by indolering** [jcranmer/idna-uts46#8]
> This code does not implement the verifyDNSLength parameter of the UTS #46 algorithm (largely because the WHATWG URL specification does not use said parameter)

The [URL standard uses this parameter](https://url.spec.whatwg.org/#idna) and **not** checking for this certainly limits its utility as a domain/subdomain pre-processor.

**Comment by jcranmer** [comment]
This is fixed by 9e2ff191a8887c872ad172f2d72f8d4bf353aef8.
